[workspace]
channels = ["conda-forge"]
name = "mathFormer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
train = "PYTHONPATH=. python3 src/train.py"
evaluate = "PYTHONPATH=. python3 src/evaluate.py"

[dependencies]
python = ">=3.13.7,<3.14"
pytorch = ">=2.8.0,<3"
notebook = ">=7.4.7,<8"
